name: Loca Tweet Bot

on:
  # schedule:
  #  - cron: "0 * * * *"        # 毎時0分（UTC）。本運用では毎日1回、SNSで読まれやすい時間帯にする
  workflow_dispatch:            # 手動実行ボタン

permissions:
  contents: write               # data.json（重複確認用） をコミットするため

concurrency:
  group: loca-x-bot
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          IFTTT_WEBHOOK_URL: ${{ secrets.IFTTT_WEBHOOK_URL }}
          DRY_RUN: none
          MAX_AGE_HOURS: '168'   # LT用: 7日までを対象に（本運用では 24 に戻す）
        run: |
          python main.py

      # data.json が更新されたらコミット＆プッシュ（重複防止のため状態を永続化）
      - name: Commit & push state (data.json)
        if: hashFiles('data.json') != ''
        run: |
          if [ -n "$(git status --porcelain data.json)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add data.json
            git commit -m "chore: update data.json (posted IDs) [skip ci]" || true
            git push || true
          fi